[tls.options]

  [tls.options.default]
    minVersion = "VersionTLS12"

    cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256"
    ]

    sniStrict = true

[http]
  # Add the router
  [http.routers]
    [http.routers.plex]
      entryPoints = ["web-secure"]
      service = "service-plex"
      rule = "Host(`plex.example.org`)"     #Cambiare con il proprio dominio
      certresolver="certificato"
      [[http.routers.plex.tls.domains]]
        main = "*.example.org"              #Cambiare con il proprio dominio

  # Add the service
    [http.services.service-plex]
      [http.services.service-plex.loadBalancer]
        [[http.services.service-plex.loadBalancer.servers]]
          url = "https://192.168.1.123:32400"
